// <auto-generated />
using Cep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMixApi.Migrations
{
    [DbContext(typeof(CepDbContext))]
    [Migration("20241016133756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMixApi.Data.Models.CEP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("CEP");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<string>("Gia")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("GIA");

                    b.Property<int>("Ibge")
                        .HasColumnType("int")
                        .HasColumnName("IBGE");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("LOCALIDADE");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("UF");

                    b.Property<int>("Unidade")
                        .HasColumnType("int")
                        .HasColumnName("UNIDADE");

                    b.HasKey("Id")
                        .HasName("IDX_Id");

                    b.ToTable("CEP", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
